name: Android Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.2
  FLUTTER_VERSION: 3.24.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 33
        build-tools: 33.0.0
        target: android-33

    - name: Flet Build Android
      run: |
        flutter config --no-analytics
        flutter build apk --release --no-sound-null-safety --build-number=$BUILD_NUMBER --build-name=$BUILD_VERSION

    - name: Upload Android Artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-build-artifact
        path: build/app/outputs/flutter-apk/app-release.apk
        if-no-files-found: error
        overwrite: false

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Release
        uses: jasondavis303/tag-and-release-and-upload@v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: v${{ env.BUILD_VERSION }}
          assets: '[ "android-build-artifact" ]'
          overwrite: false
